version: '3'

services:
  mlflow:
    build: .
    # scale: 2
    ports:
      - 8080:8080
    volumes:
      - data:/app/data
    environment:
      BACKEND_URI: sqlite:////app/data/mlflow.sqlite
      ARTIFACT_ROOT: /app/data/artifacts
      MLFLOW_VERSION: '1.23.1'
      MLFLOW_PORT: '8080'
      MLFLOW_HOST: '0.0.0.0'

volumes:
  data:
