name: "Docs build"

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'jobs_artifacts/job.json'
      - 'mergernet/**'
      - 'scripts/**'
      - '.github/workflows/main.yaml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
        cache-dependency-path: docs-requirements.txt

    - name: install deps
      run: |
        pip install -U wheel
        pip install -r docs-requirements.txt

    - name: build docs
      run: |
        cd docs
        python artifacts.py
        make html &> /dev/null

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
